#!/bin/bash

LOCALGROUP=10000

function confirm() {
if [ $1 -ne 0 ]; 
then 
	shift
	echo "$*" 
	read dummy
fi
}


function check_first ()  {
REZ=$(getent group admin)
if [ $? -ne 0 ] ;
then
	echo "admin group do not exit admin:120"
exit
fi
REZ=$(echo $REZ | cut -d ':' -f 3)
if [ ${REZ:=0} -ne 120 ];
then
	echo "admin group not id 120 admin:120" 
exit
fi

}

#main

df /data > /dev/null 2>&1 
if [ $? -ne 0 ];
then
	echo -n "Adding /data filesystem (^C to exit) ?"
	read dummy 
	echo "/dev/sda4               /data           ext4    defaults        0 2" >> /etc/fstab
	[[ ! -d /data ]] && mkdir /data
	mount /data
	if [ $? -ne 0];
	then
		echo "/data mount failed"
		exit
	fi
fi

echo "Creating group local"
groupadd -g $LOCALGROUP local
confirm $? "Error creating local group $LOCALGROUP"

getent group admin > /dev/null
if [ $? -ne 0 ] ;
then
	echo "creating admin (119) group"
	groupadd -g 119 admin
fi

for i in $(ls -d /data/home/*) ;
do
	LOCALUID=$(ls -ladn $i | awk '{print $3}')
	LOCALGID=$(ls -ladn $i | awk '{print $4}')
	USERNAME=$(basename $i)
	if [ $LOCALGID -ne $LOCALGROUP ];
	then
		echo "Ignoring $USERNAME $LOCALUID $LOCALGID"
	else
		useradd -u $LOCALUID -g local -d /home/$USERNAME -s /bin/bash  $USERNAME 
		ln -s /data/home/$USERNAME /home/$USERNAME
		usermod -G admin pierre
	fi
	if [ $USERNAME == "pierre" ] ; 
	then
	getent group wheel > /dev/nul 2>&1 
	if [ $? -eq 0 ]; 
	then
		usermod -G wheel pierre
	fi
	fi
done

if [ ! -r /var/log/messages ] ;
then
	echo "warnign messages file is not readable"
	echo "#destination messages { file("/var/log/messages" group("admin") perm(0640)); };"
fi

echo "Dont forget to update password"

